author: &author
  name: ArÄ¥imedeÏ‚ MontegasppÎ± CacilhÎ±Ï‚
  email: montegasppa@cacilhas.info
  url: //montegasppa.cacilhas.info/author.html
  contacts:
    devto:
      name: DEV Profile ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»
      title: DEV Profile ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»
      url: https://dev.to/cacilhas
    itch:
      name: Itch.io
      title: Itch.io
      url: https://cacilhas.itch.io/
    twitter:
      name: Twitter
      title: ArÄ¥imedeÏ‚ â„³ontegasppÎ±
      url: https://twitter.com/Montegasppa
      image:
        source: //cacilhas.info/img/twitter.png
        style:
          width: 24px
          height: 24px
    patreon:
      name: Patreon
      title: â„³ontegasppÎ±
      url: https://www.patreon.com/cacilhas
      image:
        source: //cacilhas.info/img/patreon.png
        style:
          width: 24px
          height: 24px
    bandcamp:
      name: Bandcamp
      title: Le Obscur EssenteÏ‚
      url: https://montegasppa.bandcamp.com/releases
      image:
        source: //cacilhas.info/img/le-obscur-essentes.jpg
        style:
          width: 24px
          height: 24px
    exercism:
      name: Exercism
      title: Exercism
      url: https://exercism.org/profiles/cacilhas
      image:
        source: //cacilhas.info/img/exercism.png
        style:
          width: 24px
          height: 24px
    github:
      name: Github
      url: https://github.com/cacilhas/
      image:
        source: //cacilhas.info/img/github.png
        style:
          width: 24px
          height: 20px
    mastodon:
      name: Mastodon
      title: Mastodon
      url: https://mas.to/@cacilhas
      image:
        source: //cacilhas.info/img/mastodon.png
        style:
          width: 22px
          height: 24px
          swidth: 11px
          sheight: 12px
    facebook:
      name: Facebook
      title: Archimedes Montegasppa
      url: https://www.facebook.com/archimedes.montegasppa.3
      image:
        source: //cacilhas.info/img/facebook.png
        style:
          width: 24px
          height: 24px
    linkedin:
      name: LinkedIn
      title: Rodrigo Cacilhas
      url: https://br.linkedin.com/in/rodrigocacilhas
      image:
        source: //cacilhas.info/img/linkedin.png
        style:
          width: 24px
          height: 24px

description: Musician, senior software engineer, autistic person, and autistic parent - not necessarily in ğ“­ğ“²ğ“¼â€€ğ“¸ğ“»ğ“­ğ“®ğ“»
favicon: /img/favicon.ico
lang: en
image: /img/title-background.jpg
site: &site //montegasppa.cacilhas.info
title: &title â„³ontegasppÎ± and Giulia C.â€™s Thoughts

license:
  name: CC-BY 4.0
  url: http://creativecommons.org/licenses/by/4.0/deed
  image: https://i.creativecommons.org/l/by/4.0/80x15.png

blog:
  author: *author
  url: *site
  title: *title

cacilhas:
  title: â„­acilhÎ±Ï‚.INFO
  url: //cacilhas.info

hondaj:
  title: Ä¤Ã¸Å…ÄÎ”jÌ†â‚€
  url: //hondaj.cacilhas.info/

kodumaro:
  title: Kodumaro
  url: //kodumaro.cacilhas.info/

mosaicolivre:
  title: Mosaico Livre
  url: https://claudiotorcato.wordpress.com/

todasfridas:
  title: Todas Fridas
  url: https://www.todasfridas.com.br/

vortaro:
  title: Konsulta Vortaro
  url: //vortaro.cacilhas.info/

waltercruz:
  title: Walter Cruz
  url: https://waltercruz.com/

googlead:
  client: ca-pub-5741846017654057
  id: UA-99357497-1

bandcamp:
  le-obscur-essentes: >
    <iframe style="border: 0; width: 100%; height: 42px;"
    src="https://bandcamp.com/EmbeddedPlayer/album=1353428037/size=small/bgcol=333333/linkcol=0f91ff/transparent=true/"
    seamless><a href="https://montegasppa.bandcamp.com/album/le-obscur-essente">Le Obscur EssenteÏ‚ by MontegasppÎ±</a></iframe>
  nimbo: >
    <iframe style="border: 0; width: 100%; height: 42px;"
    src="https://bandcamp.com/EmbeddedPlayer/album=581709135/size=small/bgcol=ffffff/linkcol=0687f5/transparent=true/"
    seamless><a href="https://montegasppa.bandcamp.com/album/o-nimbo">O Nimbo by MontegasppÎ± feat. SÃ¦kla</a></iframe>
  the-ravening-crow: >
    <iframe style="border: 0; width: 100%; height: 42px;"
    src="https://bandcamp.com/EmbeddedPlayer/album=979506318/size=small/bgcol=ffffff/linkcol=0687f5/transparent=true/"
    seamless><a href="https://montegasppa.bandcamp.com/album/the-ravening-crow">The Ravening Crow by MontegasppÎ±</a></iframe>
